// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cponvxfeenrkeacdlabl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwb252eGZlZW5ya2VhY2RsYWJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNTIzODYsImV4cCI6MjA2MDYyODM4Nn0.fhbu6OkCKzEL3UN3HkAcB5HvuDF3-aISKqiOQLH-1KI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);